#!/usr/bin/env sh
# Adapts a project generated by `solana-mobile webshell init` to the game. Run it after every `init`
# (init rewrites the template files); it is idempotent, so running it twice changes nothing.
#
#   1. Landscape only: android:screenOrientation="sensorLandscape" on MainActivity.
#   2. No pull-to-refresh: the template reloads the page on a downward swipe whenever the page cannot
#      scroll up, which for a full-screen canvas game is every swipe down (a reload mid-raid).
#   3. Immersive full screen: hides the status and navigation bars and hides them again whenever the
#      app gets focus back (for example after the wallet app returns).
#
# Usage: ./patch-android.sh [project-dir]   (default: android)
set -eu

dir="${1:-android}"
manifest="$dir/app/src/main/AndroidManifest.xml"
activity="$(find "$dir/app/src/main/java" -name MainActivity.kt 2>/dev/null | head -n 1)"

if [ ! -f "$manifest" ] || [ -z "$activity" ]; then
  echo "patch-android: no webshell project in '$dir' (run 'webshell init' first)" >&2
  exit 1
fi

# 1. Landscape.
if ! grep -q 'android:screenOrientation' "$manifest"; then
  perl -0pi -e 's/(android:name="\.MainActivity")/$1\n            android:screenOrientation="sensorLandscape"/' "$manifest"
fi

# 2. Pull-to-refresh off: report that the page can always scroll up, so the gesture never starts.
perl -0pi -e 's/setOnChildScrollUpCallback \{ _, _ -> webView\.canScrollVertically\(-1\) \}/setOnChildScrollUpCallback { _, _ -> true } \/\/ SPOILS: no pull-to-refresh in the game/' "$activity"

# 3. Immersive full screen.
if ! grep -q 'SPOILS: immersive' "$activity"; then
  perl -0pi -e 's/(import androidx\.activity\.enableEdgeToEdge\n)/$1import androidx.core.view.WindowCompat\nimport androidx.core.view.WindowInsetsCompat\nimport androidx.core.view.WindowInsetsControllerCompat\n/' "$activity"
  perl -0pi -e 's/(class MainActivity : ComponentActivity\(\) \{\n)/$1    \/\/ SPOILS: immersive full screen, bars come back only on an edge swipe.\n    override fun onWindowFocusChanged(hasFocus: Boolean) {\n        super.onWindowFocusChanged(hasFocus)\n        if (hasFocus) {\n            WindowCompat.getInsetsController(window, window.decorView).apply {\n                hide(WindowInsetsCompat.Type.systemBars())\n                systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE\n            }\n        }\n    }\n\n/' "$activity"
fi

fail=0
grep -q 'android:screenOrientation="sensorLandscape"' "$manifest" || { echo "patch-android: landscape patch did not apply" >&2; fail=1; }
grep -q 'setOnChildScrollUpCallback { _, _ -> true }' "$activity" || { echo "patch-android: pull-to-refresh patch did not apply (template changed?)" >&2; fail=1; }
grep -q 'override fun onWindowFocusChanged' "$activity" && grep -q 'import androidx.core.view.WindowCompat' "$activity" \
  || { echo "patch-android: immersive patch did not apply (template changed?)" >&2; fail=1; }
[ "$fail" -eq 0 ] && echo "patch-android: landscape, no pull-to-refresh, immersive -> $dir"
exit "$fail"
