// Downloads the three Google fonts the web app takes from next/font (app/layout.tsx), latin subset,
// into src/fonts/ with a fonts.css next to them: the iDos build hosts everything itself.
// Run once (the files are committed): node scripts/fetch-fonts.mjs
import { mkdirSync, writeFileSync } from "node:fs";

const out = new URL("../src/fonts/", import.meta.url).pathname;
mkdirSync(out, { recursive: true });
const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130 Safari/537.36";
const families = [
  ["Luckiest Guy", "family=Luckiest+Guy"],
  ["Nunito", "family=Nunito:wght@200..1000"],
  ["Press Start 2P", "family=Press+Start+2P"],
];
let css = "/* Generated by scripts/fetch-fonts.mjs (Google Fonts, SIL Open Font License). */\n";
for (const [name, q] of families) {
  const text = await (await fetch(`https://fonts.googleapis.com/css2?${q}&display=swap`, { headers: { "user-agent": UA } })).text();
  // Only the latin block (the game's copy is English).
  const blocks = text.split("/* ").filter((b) => b.startsWith("latin */"));
  if (!blocks.length) throw new Error(`no latin block for ${name}`);
  for (const b of blocks) {
    const url = /url\((https:[^)]+\.woff2)\)/.exec(b)[1];
    const file = `${name.replace(/\s+/g, "-").toLowerCase()}.woff2`;
    writeFileSync(out + file, Buffer.from(await (await fetch(url)).arrayBuffer()));
    css += "/* " + b.replace(url, `./${file}`);
  }
}
writeFileSync(out + "fonts.css", css);
console.log("fonts written to", out);
